.\"
.\" gde2-about manual page.
.\" (C) 2010 Vincent Untz (vuntz@gnome.org)
.\"
.TH GDE2-ABOUT 1 "GDE2"
.SH NAME
gde2-about \- Learn more about GDE2
.SH SYNOPSIS
.B gde2-about [\-\-gde2-version]
.SH DESCRIPTION
The \fIgde2-about\fP program is a tool to learn more about GDE2 and
who creates GDE2. It contains an introduction about the project, and
lists all contributors.
.PP
The list of contributors used by \fIgde2-about\fP is the list of
GDE2 Foundation members.
.SH OPTIONS
The following options are supported:
.TP
.I "--gde2-version"
Output the GDE2 version instead of running a graphical interface.
.SH BUGS
If you find bugs in the \fIgde2-about\fP program, please report
these on http://bugzilla.gnome.org.
