.\"
.\" gde2-color-select manual page.
.\" (C) 2015 Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
.\"
.TH gde2-color-select 1 "GDE2"
.SH NAME
gde2-color-select \- Select a color from a palette or from screen
.SH SYNOPSIS
.B gde2-color-select [<gtk-options>]
.SH DESCRIPTION
The \fIgde2-color-select\fP program is a tool to pick a color from a
color palette or from screen. It is not meant to be used on its own, but
as a GDE2 Desktop helper application.
.SH OPTIONS
The \fBgde2-color-select\fR tool supports all known GTK options, but has no options of its own.
.SH BUGS
If you find bugs in the \fIgde2-color-select\fP program, please report
these on https://github.com/gde2-desktop/gde2-desktop/issues.
